spring:
  application:
    name: greeting-service
  cloud:
    config:
      profile: dev
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Olá"
  default-value: "Default"